x-common-config:
  &common-config
  network_mode: host
  ipc: host

x-cpu-display: &cpu-display
  env_file: .cpu_display.env

x-gpu-display: &gpu-display
  runtime: nvidia
  env_file: .gpu_display.env

services:
  panther_gazebo:
    image: husarion/panther-gazebo:humble-sonoma
    <<:
      - *common-config
      - *gpu-display
    environment:
      - PANTHER_IMU_ORIENTATION_R=0.0 # IMU is roataded on Sonoma world what caused orientation issue
      - PANTHER_IMU_ORIENTATION_P=0.0
      - PANTHER_IMU_ORIENTATION_Y=0.0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/components.yaml:/config/components.yaml
    command: >
      ros2 launch panther_gazebo simulation.launch.py
        components_config_path:=/config/components.yaml
        fuse_gps:=True
        gz_world:=/ros2_ws/src/husarion_gz_worlds/worlds/sonoma_raceway.sdf
        localization_mode:=enu
        namespace:=panther

  foxglove:
    image: husarion/foxglove:1.84.0
    ports:
      - 8080:8080
      - 8765:8765
    volumes:
      - ./config/layout.json:/foxglove/default-layout.json
    environment:
      - DS_TYPE=foxglove-websocket
      - DS_PORT=8765
      - DS_HOST=foxglove-ds
      - UI_PORT=8080
      - DISABLE_CACHE=true
      - DISABLE_INTERACTION=false

  foxglove-ds:
    image: husarion/foxglove-bridge:humble-0.7.3-20240108
    command: ros2 launch foxglove_bridge foxglove_bridge_launch.xml
      port:=8765
      capabilities:=[clientPublish,connectionGraph,assets]
