x-net-config: &net-config
  network_mode: host
  ipc: host
  env_file: ../net.env

services:
  lsc16-lidar:
    build:
      dockerfile: Dockerfile
    <<: *net-config
    restart: unless-stopped
    volumes:
      - ./config/lslidar_c16.yaml:/ros_ws/src/Lslidar_ROS2_driver/lslidar_driver/params/lslidar_c16.yaml
      - ./config/lslidar_c16_launch.py:/ros_ws/src/Lslidar_ROS2_driver/lslidar_driver/launch/lslidar_c16_launch.py
    command: ros2 launch lslidar_driver lslidar_c16_launch.py

  foxglove:
    image: husarion/foxglove:1.84.0-20240119
    restart: unless-stopped
    ports:
      - 8080:8080
    # volumes:
      # - ./config/foxglove.json:/foxglove/default-layout.json
      # - ./config/panther_ouster.urdf:/src/panther.urdf
    environment:
      - DS_TYPE=foxglove-websocket
      - DS_PORT=8765
      - DS_HOST=foxglove-ds
      - UI_PORT=8080
      - DISABLE_CACHE=true
      - DISABLE_INTERACTION=false

  foxglove-ds:
    image: husarion/foxglove-bridge:humble-0.7.4-20240320
    <<: *net-config
    restart: unless-stopped
    command: ros2 launch foxglove_bridge foxglove_bridge_launch.xml port:=8765 capabilities:=[clientPublish,connectionGraph,assets]
